trigger: none
pool: Git_Azure_Infra

jobs:
# - job: TerraformInit
#   displayName: Terraform_Init
#   steps: 
#   - task: TerraformTaskV4@4
#     inputs:
#       provider: 'azurerm'
#       command: 'init'
#       workingDirectory: '$(System.DefaultWorkingDirectory)/Env/Dev'
#       backendServiceArm: 'SK_Azure_Git_Infra'
#       backendAzureRmResourceGroupName: 'Shubham_Singhvi'
#       backendAzureRmStorageAccountName: 'shubhamsinghvi86967'
#       backendAzureRmContainerName: 'infracontainer'
#       backendAzureRmKey: 'terraform,tfstate'

- job: Terraforminitplan
  displayName: Terraform_Init & Plan
  steps:
  - task: TerraformTaskV4@4
    displayName: Terraform_init
    inputs:
      provider: 'azurerm'      
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)/Env/Dev'
      backendServiceArm: 'SK_Azure_Git_Infra'
      backendAzureRmResourceGroupName: 'Shubham_Singhvi'
      backendAzureRmStorageAccountName: 'shubhamsinghvi86967'
      backendAzureRmContainerName: 'infracontainer'
      backendAzureRmKey: 'terraform,tfstate'
 
  - task: TerraformTaskV4@4
    displayName: Terraform_Plan
    inputs:
      provider: 'azurerm'
      command: 'plan'
      workingDirectory: '$(System.DefaultWorkingDirectory)/Env/Dev'
      environmentServiceNameAzureRM: 'SK_Azure_Git_Infra'

- job: Validation
  displayName: Manual Validation
  dependsOn: Terraforminitplan
  pool: server
  steps:
  - task: ManualValidation@1
    inputs:
        notifyUsers: 'shubham.singhvi@example.com'  # <- Use actual email or Azure DevOps user ID
        instructions: 'Please review and approve the Terraform Plan.'
        
- job: terraformapply
  displayName: Terraform Apply
  dependsOn: Validation
  steps:
  
  - task: TerraformTaskV4@4
    displayName: Terraform_init
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)/Env/Dev'
      commandOptions: '--upgrade'
      backendServiceArm: 'SK_Azure_Git_Infra'
      backendAzureRmResourceGroupName: 'Shubham_Singhvi'
      backendAzureRmStorageAccountName: 'shubhamsinghvi86967'
      backendAzureRmContainerName: 'infracontainer'
      backendAzureRmKey: 'terraform.tfstate'
  - task: TerraformTaskV4@4
    displayName: Terraform_Apply
    inputs:
      provider: 'azurerm'
      command: 'apply'
      workingDirectory: '$(System.DefaultWorkingDirectory)/Env/Dev'
      environmentServiceNameAzureRM: 'SK_Azure_Git_Infra'