trigger: none
pool: Git_Azure_Infra

steps:
- task: TerraformTaskV4@4
  displayName: Terraform_Init
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Env/Dev'
    backendServiceArm: 'SK_Azure_Git_Infra'
    backendAzureRmResourceGroupName: 'Shubham_Singhvi'
    backendAzureRmStorageAccountName: 'shubhamsinghvi86967'
    backendAzureRmContainerName: 'infracontainer'
    backendAzureRmKey: 'terraform.tfstate'

- task: TerraformTaskV4@4
  displayName:  Terraform_Plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Env/Dev'
    environmentServiceNameAzureRM: 'SK_Azure_Git_Infra'


- task: TerraformTaskV4@4
  displayName: Terraform_Apply
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Env/Dev'
    commandOptions: '--auto-approve'
    environmentServiceNameAzureRM: 'SK_Azure_Git_Infra'