trigger: none
pool: Git_Azure_Infra

stages:
- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Env/Dev'
    backendServiceArm: 'Azure_Git_Infra'
    backendAzureRmResourceGroupName: 'Shubham_Singhvi'
    backendAzureRmStorageAccountName: 'shubhamsinghvi8696'
    backendAzureRmContainerName: 'infracontainer'
    backendAzureRmKey: 'terraform.tfstate'

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Env/Dev'
    environmentServiceNameAzureRM: 'Azure_Git_Infra'